In [2]:
import world_bank_data as wb
import pandas as pd
import numpy as np
import seaborn as sns
import json
import wbdata 
import matplotlib.pyplot as plt

In [3]:
import pandas_datareader.data as web
import pandas_datareader as pdr

In [3]:
#getting data topics from world bank
wb.get_topics()

,value,sourceNote
id,,
1,Agriculture & Rural Development,For the 70 percent of the world's poor who liv...
2,Aid Effectiveness,Aid effectiveness is the impact that aid has i...
3,Economy & Growth,Economic growth is central to economic develop...
4,Education,Education is one of the most powerful instrume...
5,Energy & Mining,The world economy needs ever-increasing amount...
6,Environment,Natural and man-made environmental resources –...
7,Financial Sector,An economy's financial markets are critical to...
8,Health,Improving health is central to the Millennium ...
9,Infrastructure,Infrastructure helps determine the success of ...
10,Social Protection & Labor,The supply of labor available in an economy in...
11,Poverty,For countries with an active poverty monitorin...
12,Private Sector,"Private markets drive economic growth, tapping..."
13,Public Sector,Effective governments improve people's standar...
14,Science & Technology,"Technological innovation, often fueled by gove..."
15,Social Development,"Data here cover child labor, gender issues, re..."
16,Urban Development,Cities can be tremendously efficient. It is ea...
17,Gender,Gender equality is a core development objectiv...
18,Millenium development goals,
19,Climate Change,Climate change is expected to hit developing c...
20,External Debt,Debt statistics provide a detailed picture of ...
21,Trade,Trade is a key means to fight poverty and achi...

In [4]:
#getting indicators from world bank
wb.get_indicators()

,name,unit,source,sourceNote,sourceOrganization,topics
id,,,,,,
1.0.HCount.1.90usd,Poverty Headcount ($1.90 a day),,LAC Equity Lab,The poverty headcount index measures the propo...,LAC Equity Lab tabulations of SEDLAC (CEDLAS a...,Poverty
1.0.HCount.2.5usd,Poverty Headcount ($2.50 a day),,LAC Equity Lab,The poverty headcount index measures the propo...,LAC Equity Lab tabulations of SEDLAC (CEDLAS a...,Poverty
1.0.HCount.Mid10to50,Middle Class ($10-50 a day) Headcount,,LAC Equity Lab,The poverty headcount index measures the propo...,LAC Equity Lab tabulations of SEDLAC (CEDLAS a...,Poverty
1.0.HCount.Ofcl,Official Moderate Poverty Rate-National,,LAC Equity Lab,The poverty headcount index measures the propo...,LAC Equity Lab tabulations of data from Nation...,Poverty
1.0.HCount.Poor4uds,Poverty Headcount ($4 a day),,LAC Equity Lab,The poverty headcount index measures the propo...,LAC Equity Lab tabulations of SEDLAC (CEDLAS a...,Poverty
...,...,...,...,...,...,...
WP15163_4.3,"Mobile account, female (% age 15+)",,WDI Database Archives,Mobile account denotes the percentage of respo...,"Demirguc-Kunt et al., 2015, Global Financial I...","Financial Sector ,Gender"
WP15163_4.8,"Mobile account, income, poorest 40% (% ages 15+)",,WDI Database Archives,Mobile account denotes the percentage of respo...,"Demirguc-Kunt et al., 2015, Global Financial I...",Financial Sector
WP15163_4.9,"Mobile account, income, richest 60% (% ages 15+)",,WDI Database Archives,Mobile account denotes the percentage of respo...,"Demirguc-Kunt et al., 2015, Global Financial I...",Financial Sector
wpremia_F,Wage Premia for Females (the ratio of skilled ...,,Gender Disaggregated Labor Database (GDLD),,,
wpremia_M,Wage Premia for Males (the ratio of skilled m...,,Gender Disaggregated Labor Database (GDLD),,,

In [4]:
#getting countries from world bank
countries = wb.get_countries()
countries

,iso2Code,name,region,adminregion,incomeLevel,lendingType,capitalCity,longitude,latitude
id,,,,,,,,,
ABW,AW,Aruba,Latin America & Caribbean,,High income,Not classified,Oranjestad,-70.0167,12.51670
AFG,AF,Afghanistan,South Asia,South Asia,Low income,IDA,Kabul,69.1761,34.52280
AFR,A9,Africa,Aggregates,,Aggregates,Aggregates,,NaN,NaN
AGO,AO,Angola,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,IBRD,Luanda,13.2420,-8.81155
ALB,AL,Albania,Europe & Central Asia,Europe & Central Asia (excluding high income),Upper middle income,IBRD,Tirane,19.8172,41.33170
...,...,...,...,...,...,...,...,...,...
XZN,A5,Sub-Saharan Africa excluding South Africa and ...,Aggregates,,Aggregates,Aggregates,,NaN,NaN
YEM,YE,"Yemen, Rep.",Middle East & North Africa,Middle East & North Africa (excluding high inc...,Low income,IDA,Sana'a,44.2075,15.35200
ZAF,ZA,South Africa,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Upper middle income,IBRD,Pretoria,28.1871,-25.74600
ZMB,ZM,Zambia,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,IDA,Lusaka,28.2937,-15.39820
ZWE,ZW,Zimbabwe,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,Blend,Harare,31.0672,-17.83120

In [25]:
#elimination of regions
population = wb.get_series('SP.POP.TOTL', id_or_value='id', simplify_index=True, mrv=1)
df_c = countries[['region', 'name']].rename(columns={'name': 'country'}).loc[countries.region != 'Aggregates']
df['population'] = population
df['log_pop'] = np.log(population)

In [9]:
#data for Series Code
list_value_code=pd.read_excel('WDI_CETS.xls', sheet_name=1)

In [10]:
list_value_code.head()

,Series Code,Series Name,Topic,SubTopic1,SubTopic2,SubTopic3
0,AG.AGR.TRAC.NO,"Agricultural machinery, tractors",Environment,Agricultural production,NaN,NaN
1,AG.CON.FERT.PT.ZS,Fertilizer consumption (% of fertilizer produc...,Environment,Agricultural production,NaN,NaN
2,AG.CON.FERT.ZS,Fertilizer consumption (kilograms per hectare ...,Environment,Agricultural production,NaN,NaN
3,AG.LND.AGRI.K2,Agricultural land (sq. km),Environment,Land use,NaN,NaN
4,AG.LND.AGRI.ZS,Agricultural land (% of land area),Environment,Land use,NaN,NaN

In [42]:
#Series Code which contains GDP per
list_value_code[list_value_code['Series Name'].str.contains('GDP per')==True]

,Series Code,Series Name,Topic,SubTopic1,SubTopic2,SubTopic3
371,EG.GDP.PUSE.KO.PP,GDP per unit of energy use (PPP $ per kg of oi...,Environment,Energy production & use,NaN,NaN
372,EG.GDP.PUSE.KO.PP.KD,GDP per unit of energy use (constant 2011 PPP ...,Environment,Energy production & use,NaN,NaN
439,ER.GDP.FWTL.M3.KD,"Water productivity, total (constant 2010 US$ G...",Environment,Freshwater,NaN,NaN
820,NY.GDP.PCAP.CD,GDP per capita (current US$),Economic Policy & Debt,National accounts,US$ at current prices,Aggregate indicators
821,NY.GDP.PCAP.CN,GDP per capita (current LCU),Economic Policy & Debt,National accounts,Local currency at current prices,Aggregate indicators
822,NY.GDP.PCAP.KD,GDP per capita (constant 2010 US$),Economic Policy & Debt,National accounts,US$ at constant 2010 prices,Aggregate indicators
823,NY.GDP.PCAP.KD.ZG,GDP per capita growth (annual %),Economic Policy & Debt,National accounts,Growth rates,NaN
824,NY.GDP.PCAP.KN,GDP per capita (constant LCU),Economic Policy & Debt,National accounts,Local currency at constant prices,Aggregate indicators
825,NY.GDP.PCAP.PP.CD,"GDP per capita, PPP (current international $)",Economic Policy & Debt,Purchasing power parity,NaN,NaN
826,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2011 internation...",Economic Policy & Debt,Purchasing power parity,NaN,NaN
1040,SE.XPD.PRIM.PC.ZS,"Government expenditure per student, primary (%...",Education,Inputs,NaN,NaN
1042,SE.XPD.SECO.PC.ZS,"Government expenditure per student, secondary ...",Education,Inputs,NaN,NaN
1044,SE.XPD.TERT.PC.ZS,"Government expenditure per student, tertiary (...",Education,Inputs,NaN,NaN
1225,SL.GDP.PCAP.EM.KD,GDP per person employed (constant 2011 PPP $),Social Protection & Labor,Economic activity,NaN,NaN

In [52]:
#variables for the dataframe
liste = ['NY.GDP.PCAP.KD', 'NY.GDP.PCAP.PP.CD','NY.GDP.PCAP.CD','NY.GDP.MKTP.KD.ZG','NY.GDP.PCAP.KD.ZG','SP.POP.GROW',
         'FP.CPI.TOTL.ZG', 'NY.GDP.DEFL.KD.ZG', 'NE.TRD.GNFS.ZS','SP.DYN.LE00.IN','SP.POP.1564.TO.ZS','IQ.CPA.PROP.XQ',
         'MS.MIL.XPND.GD.ZS']

In [53]:
world = pd.DataFrame()

In [54]:
#getting data from world bank
world = pd.json_normalize(wbdata.get_data(liste [0]))
world = world[['countryiso3code','country.value','date']]
for i in liste:
    a = pd.json_normalize(wbdata.get_data(i))
    b = a['indicator.value'][0]
    a = a[['value']]
    a.rename(columns = {'value':b})
    world [b] = a

In [55]:
world.head()

,countryiso3code,country.value,date,GDP per capita (constant 2010 US$),"GDP per capita, PPP (current international $)",GDP per capita (current US$),GDP growth (annual %),GDP per capita growth (annual %),Population growth (annual %),"Inflation, consumer prices (annual %)","Inflation, GDP deflator (annual %)",Trade (% of GDP),"Life expectancy at birth, total (years)",Population ages 15-64 (% of total population),CPIA property rights and rule-based governance rating (1=low to 6=high),Military expenditure (% of GDP)
0,ARB,Arab World,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ARB,Arab World,2019,6428.593383,15256.376720,6584.740241,1.487633,-0.428807,1.924693,1.336016,1.504166,83.917036,NaN,62.672706,2.250000,5.412720
2,ARB,Arab World,2018,6456.278325,14985.352890,6601.825189,2.079469,0.160482,1.915913,2.458142,7.635713,86.307775,71.806825,62.661687,2.500000,6.049775
3,ARB,Arab World,2017,6445.933776,14562.367966,6108.588220,0.820847,-1.106609,1.949024,1.966826,5.955238,86.178597,71.622526,62.649628,2.166667,6.465615
4,ARB,Arab World,2016,6518.063258,14025.865608,6112.105953,3.507128,1.458590,2.019087,2.068840,0.347183,82.599449,71.436497,62.659456,2.500000,6.152311

In [56]:
world.shape

(16104, 16)